### ISSUE TITLE
Bug on CrossFactionBgs

### ISSUE THREAD

**Issue by cyberpro98** [Adeer/Crossfaction-BG#7]
I can't compile on my TrinityCore 3.3.5 the Crossfaction Script of Adeer.
I am using newer version of trinity , TrinityCore rev. c61fac843b86 2015-03-29 15:04:51 +0200 (3.3.5 branch) (Win32, Release) (worldserver-daemon)

So i bought your script and not working on my core , please fix it. 
I contacted you even on e-mail.

**Comment by Adeer** [comment]
Fixed.
